version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./sql_app.db:/app/sql_app.db

  ui:
    build: ./streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000